---
title: "Databases_SQL_HMK2"
author: "Nicol Parker"
date: "May 13, 2018"
output: 
  html_document:
    toc: true # creates table of contents
    toc_depth: 3 # determines depth to which headers are shown in the table of contents (here ##)
    toc_float: true # creates floating table of contents
    code_folding: hide #creates buttons to hide or show code
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(kableExtra)
library(dbplyr)
library(dbConnect)
library(RMySQL)

setwd('C:/Users/Nicol/Documents/GitHub/Computing_Environmental_Science/Databases_SQL_HMK2/')
```

##Data Wrangling
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
#Load Data
gaz_raw <- as.tibble(read.table('CA_Features_20180401.txt', header=TRUE, sep = '|', fill = TRUE))

#Fix column 1 name
colnames(gaz_raw)[1] <- 'FEATURE_ID'

#Create tibble with variables of interest
gaz <- select(gaz_raw,'FEATURE_ID','FEATURE_NAME', 'FEATURE_CLASS', 'STATE_ALPHA', 'COUNTY_NAME', 'PRIM_LAT_DEC','PRIM_LONG_DEC','SOURCE_LAT_DEC', 'SOURCE_LONG_DEC', 'ELEV_IN_M', 'MAP_NAME', 'DATE_CREATED', 'DATE_EDITED')

#transform data to appropriate type
gaz[,1:7] <- lapply(gaz[,1:7], as.character)
gaz[, 6:7]<- lapply(gaz[,6:7], as.numeric)
gaz$ELEV_IN_M <- as.numeric(gaz$ELEV_IN_M)
gaz$DATE_CREATED <- as.Date(gaz$DATE_CREATED, '%m/%d/%Y')
gaz$DATE_EDITED<- as.Date(gaz$DATE_EDITED, '%m/%d/%Y')

#Delete rows without coordinate info
gaz <- filter(gaz, gaz$PRIM_LAT_DEC != 'NA' | gaz$PRIM_LONG_DEC != 'NA')

#Create SQL database and connection
gaz_db<- DBI::dbConnect(RSQLite::SQLite(), path=':memory:')

#Copy over organized data to created database
copy_to(gaz_db, gaz, 'gaz', indexes = list('FEATURE_NAME', 'FEATURE_CLASS'))

#Reference database
#gaz_tbl<- tbl(conn, 'gaz')


```

##Solutions
###Question 1: Most freqently occuring feature name?
```{r}
dbGetQuery(gaz_db, 'SELECT FEATURE_NAME, 
           COUNT("FEATURE_NAME") AS "FEATURE_NAME_COUNT"
           FROM gaz
           GROUP BY "FEATURE_NAME"
           ORDER BY "FEATURE_NAME_COUNT" DESC
           LIMIT 1')
```


###Question 2: Least frequently occuring feature class?
```{r}
dbGetQuery(gaz_db, 'SELECT FEATURE_CLASS, 
           COUNT("FEATURE_CLASS") AS "FEATURE_CLASS_COUNT"
           FROM gaz
           GROUP BY "FEATURE_CLASS"
           ORDER BY "FEATURE_CLASS_COUNT"
           LIMIT 1')
```

###Question 3: What is the approximate center point of each county?
```{r, results = 'hide'}
Lat <- dbGetQuery(gaz_db, 'SELECT COUNTY_NAME, avg(PRIM_LAT_DEC)
  FROM gaz  
  GROUP BY COUNTY_NAME')
colnames(Lat) <- c('COUNTY_NAME', 'Lat')
Long <- dbGetQuery(gaz_db, 'SELECT COUNTY_NAME, avg(PRIM_LONG_DEC)
  FROM gaz  
  GROUP BY COUNTY_NAME')
  colnames(Long) <- c('COUNTY', 'Long')

Center_Point <- Lat
Center_Point$Long <- Long$Long
```

```{r}
Center_Point %>%
kable('html') %>%
kable_styling(bootstrap_options ='striped', full_width = T,position='left')%>%
  scroll_box(width ='500px', height = '500px')

```

###Question 4: What are the fractions of manmade and natural features in each county?
```{r, results='hide', message=FALSE}
Unique_Class <- dbGetQuery(gaz_db, 'SELECT FEATURE_CLASS
                           FROM gaz
                           GROUP BY FEATURE_CLASS')

#filter out natural features
natural <- slice(Unique_Class,c(3,8,9,10,11,12,13,15,17:21,23,27:32,34:37,39,40:41,46,48,49,52:55,61))

#filter manmade features
manmade <- anti_join(Unique_Class, natural)

#Create ID columns
natural$type <- 'natural'
manmade$type <- 'manmade'

#combine natural and manmade features to single tibble
FEATURE_TYPE <- rbind(natural, manmade)

Unique_Class$type <- match(Unique_Class$FEATURE_CLASS,natural$FEATURE_CLASS, nomatch = 0)

for(i in 1:nrow(Unique_Class)){ 
if(Unique_Class$type[i]==0){Unique_Class$type[i]='manmade'}
  else{
    Unique_Class$type[i]='natural'}}

copy_to(gaz_db, Unique_Class)

County_Feature_Type <- dbGetQuery(gaz_db, 'SELECT gaz.COUNTY_NAME, Unique_Class.type
  FROM gaz 
  JOIN Unique_Class
  ON gaz.FEATURE_CLASS = Unique_Class.FEATURE_CLASS')

#Copy table to database
copy_to(gaz_db, County_Feature_Type, overwrite = TRUE)

#Count of manmade and natural features by county
Manmade<- dbGetQuery(gaz_db, 'SELECT COUNTY_NAME, COUNT(type) AS COUNT_TYPE_MANMADE
          FROM County_Feature_Type
          WHERE type = "manmade"
          GROUP BY COUNTY_NAME', overwrite = TRUE)
copy_to(gaz_db, Manmade)
  
Natural <- dbGetQuery(gaz_db, 'SELECT COUNTY_NAME, COUNT(type) AS COUNT_TYPE_NATURAL
          FROM County_Feature_Type
          WHERE type = "natural"
          GROUP BY COUNTY_NAME')
copy_to(gaz_db, Natural)

Summary_County_Features <- dbGetQuery(gaz_db, 'SELECT * FROM Manmade
  JOIN Natural
  ON Natural.COUNTY_NAME=Manmade.COUNTY_NAME')
Summary_County_Features <- select(Summary_County_Features, -(COUNTY_NAME..3))

Summary_County_Features$FRACTION_MANMADE <- Summary_County_Features$COUNT_TYPE_MANMADE/(Summary_County_Features$COUNT_TYPE_MANMADE + Summary_County_Features$COUNT_TYPE_NATURAL)

Summary_County_Features$FRACTION_NATURAL <- 1-Summary_County_Features$FRACTION_MANMADE
```

```{r}
Summary_County_Features %>%
kable('html') %>%
kable_styling(bootstrap_options ='striped', full_width = T,position='left')%>%
  scroll_box(width ='1000px', height = '500px')

```